// Code generated by gen; DO NOT EDIT.

//go:build windows

package discord

import "syscall"

func openLibraryInternal(name string) (uintptr, error) {
	h, err := syscall.LoadLibrary(name)
	return uintptr(h), err
}
