// Code generated by gen; DO NOT EDIT.

//go:build !windows

package discord

import "github.com/ebitengine/purego"

func openLibraryInternal(name string) (uintptr, error) {
	return purego.Dlopen(name, purego.RTLD_NOW)
}
